/**
 * Paint white rectangles + labels on top of the source PDF at every
 * match coordinate produced by `span-matcher`. The output is a standard
 * PDF byte stream ready to hand to a Blob / download.
 *
 * Why layout-preserving overlay (rather than a rebuilt-text PDF):
 * rebuilt PDFs lose fonts, embedded artwork, seals, and signature
 * placeholders; a white rectangle + label keeps every non-redacted
 * visual intact. See SP-3 brainstorm key decision #1.
 *
 * Metadata scrubbing is mandatory, not cosmetic: authors / creators /
 * producers can reveal the uploading user's name even when the body is
 * redacted. The output deliberately identifies as "Redline" so the
 * provenance of the file is unambiguous.
 */

import { PDFDocument, PDFName, PDFRef, StandardFonts, rgb } from "pdf-lib";
import type { PdfMatch } from "./types";

/**
 * Build the redacted PDF bytes.
 *
 * The output preserves the original page dimensions, fonts, and vector
 * content — only the rectangles and text labels are new draw ops
 * layered on top.
 *
 * Label font: Helvetica. StandardFonts embeds without pulling external
 * files; supports ASCII role labels like `[Provider]` / `[Email 1]`.
 * Non-ASCII role labels currently render as boxes — not a real risk
 * today because labels are generated by the pipeline, not user-typed.
 */
export async function buildRedactedPdf(
  bytes: ArrayBuffer,
  matches: PdfMatch[],
): Promise<Uint8Array> {
  // `updateMetadata: false` disables pdf-lib's default behaviour of
  // stamping itself as Producer on load. We set the producer ourselves
  // below so the output clearly identifies as generated by Redline.
  const doc = await PDFDocument.load(bytes, {
    ignoreEncryption: false,
    updateMetadata: false,
  });
  const helv = await doc.embedFont(StandardFonts.Helvetica);

  // Group by page once so we draw in page order without re-paging the
  // document for every match.
  const byPage = new Map<number, PdfMatch[]>();
  for (const m of matches) {
    const list = byPage.get(m.page);
    if (list) list.push(m);
    else byPage.set(m.page, [m]);
  }

  for (const [pageNum, pageMatches] of byPage) {
    // pdf-lib is 0-indexed; PdfMatch.page is 1-indexed.
    const page = doc.getPage(pageNum - 1);
    for (const m of pageMatches) {
      // Expand the rect by 1pt above and below the glyph baseline so
      // descenders (g, p, q, y, j) aren't sliced off. pdfjs reports
      // `y` at the baseline and `h` as the font's ascent height;
      // without this margin the rect leaks the bottom of the redacted
      // text.
      const rectY = m.y - 1;
      const rectHeight = m.h + 2;

      page.drawRectangle({
        x: m.x,
        y: rectY,
        width: m.w,
        height: rectHeight,
        color: rgb(1, 1, 1),
        borderColor: rgb(0, 0, 0),
        borderWidth: 0.5,
      });

      // Cap label size at 9pt so long role labels like `[Provider]`
      // fit inside small-font redactions (footnotes, header caps).
      const size = Math.min(m.h * 0.7, 9);
      page.drawText(m.label, {
        x: m.x + 2,
        y: rectY + 1,
        size,
        font: helv,
        color: rgb(0, 0, 0),
      });
    }
  }

  // Strip every metadata field that could leak identity.
  doc.setTitle("");
  doc.setAuthor("");
  doc.setSubject("");
  doc.setKeywords([]);
  doc.setProducer("Redline");
  doc.setCreator("Redline");
  doc.setCreationDate(new Date());
  doc.setModificationDate(new Date());

  // pdf-lib's set* helpers only mutate the /Info dict. Office suites
  // (Word, InDesign, Acrobat) also emit an XMP metadata stream
  // attached to the catalog under /Metadata, which duplicates
  // identifying fields (dc:creator, xmp:CreatorTool, xmpMM:DocumentID).
  // pdf-lib has no public API to edit XMP; dropping the reference
  // (tolerated by Acrobat/Reader) AND the indirect stream object is
  // the only way to guarantee those fields cannot leak — pdf-lib's
  // `save()` would otherwise re-emit the orphan stream intact, with
  // the original identifying payload readable in the raw output bytes.
  const metadataKey = PDFName.of("Metadata");
  const metadataRef = doc.catalog.get(metadataKey);
  doc.catalog.delete(metadataKey);
  if (metadataRef instanceof PDFRef) {
    doc.context.delete(metadataRef);
  }

  return doc.save();
}
